upstream nodeapp {
    server app:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://nodeapp;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
